#
# Autogenerated by ElasticSearch::Transport::ThriftBackend::Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package ElasticSearch::Transport::ThriftBackend::Constants;
require 5.6.0;
use strict;
use warnings;
use ElasticSearch::Transport::ThriftBackend::Thrift;


1;
