#
# Autogenerated by ElasticSearch::Transport::ThriftBackend::Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
require 5.6.0;
use strict;
use warnings;
use ElasticSearch::Transport::ThriftBackend::Thrift;

use ElasticSearch::Transport::ThriftBackend::Types;

# HELPER FUNCTIONS AND STRUCTURES

package ElasticSearch::Transport::ThriftBackend::Rest_execute_args;
use base qw(Class::Accessor);
ElasticSearch::Transport::ThriftBackend::Rest_execute_args->mk_accessors( qw( request ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{request} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{request}) {
      $self->{request} = $vals->{request};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'Rest_execute_args';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1)
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == ElasticSearch::Transport::ThriftBackend::TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^1$/ && do{      if ($ftype == ElasticSearch::Transport::ThriftBackend::TType::STRUCT) {
        $self->{request} = new ElasticSearch::Transport::ThriftBackend::RestRequest();
        $xfer += $self->{request}->read($input);
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('Rest_execute_args');
  if (defined $self->{request}) {
    $xfer += $output->writeFieldBegin('request', ElasticSearch::Transport::ThriftBackend::TType::STRUCT, 1);
    $xfer += $self->{request}->write($output);
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package ElasticSearch::Transport::ThriftBackend::Rest_execute_result;
use base qw(Class::Accessor);
ElasticSearch::Transport::ThriftBackend::Rest_execute_result->mk_accessors( qw( success ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{success} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{success}) {
      $self->{success} = $vals->{success};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'Rest_execute_result';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1)
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == ElasticSearch::Transport::ThriftBackend::TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^0$/ && do{      if ($ftype == ElasticSearch::Transport::ThriftBackend::TType::STRUCT) {
        $self->{success} = new ElasticSearch::Transport::ThriftBackend::RestResponse();
        $xfer += $self->{success}->read($input);
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('Rest_execute_result');
  if (defined $self->{success}) {
    $xfer += $output->writeFieldBegin('success', ElasticSearch::Transport::ThriftBackend::TType::STRUCT, 0);
    $xfer += $self->{success}->write($output);
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package ElasticSearch::Transport::ThriftBackend::RestIf;

use strict;


sub execute{
  my $self = shift;
  my $request = shift;

  die 'implement interface';
}

package ElasticSearch::Transport::ThriftBackend::RestRest;

use strict;


sub new {
  my ($classname, $impl) = @_;
  my $self     ={ impl => $impl };

  return bless($self,$classname);
}

sub execute{
  my ($self, $request) = @_;

  $request = ($request->{'request'}) ? $request->{'request'} : undef;
  return $self->{impl}->execute($request);
}

package ElasticSearch::Transport::ThriftBackend::RestClient;


use base qw(ElasticSearch::Transport::ThriftBackend::RestIf);
sub new {
  my ($classname, $input, $output) = @_;
  my $self      = {};
  $self->{input}  = $input;
  $self->{output} = defined $output ? $output : $input;
  $self->{seqid}  = 0;
  return bless($self,$classname);
}

sub execute{
  my $self = shift;
  my $request = shift;

    $self->send_execute($request);
  return $self->recv_execute();
}

sub send_execute{
  my $self = shift;
  my $request = shift;

  $self->{output}->writeMessageBegin('execute', ElasticSearch::Transport::ThriftBackend::TMessageType::CALL, $self->{seqid});
  my $args = new ElasticSearch::Transport::ThriftBackend::Rest_execute_args();
  $args->{request} = $request;
  $args->write($self->{output});
  $self->{output}->writeMessageEnd();
  $self->{output}->getTransport()->flush();
}

sub recv_execute{
  my $self = shift;

  my $rseqid = 0;
  my $fname;
  my $mtype = 0;

  $self->{input}->readMessageBegin(\$fname, \$mtype, \$rseqid);
  if ($mtype == ElasticSearch::Transport::ThriftBackend::TMessageType::EXCEPTION) {
    my $x = new ElasticSearch::Transport::ThriftBackend::TApplicationException();
    $x->read($self->{input});
    $self->{input}->readMessageEnd();
    die $x;
  }
  my $result = new ElasticSearch::Transport::ThriftBackend::Rest_execute_result();
  $result->read($self->{input});
  $self->{input}->readMessageEnd();

  if (defined $result->{success} ) {
    return $result->{success};
  }
  die "execute failed: unknown result";
}
package ElasticSearch::Transport::ThriftBackend::RestProcessor;

use strict;


sub new {
    my ($classname, $handler) = @_;
    my $self      = {};
    $self->{handler} = $handler;
    return bless ($self, $classname);
}

sub process {
    my ($self, $input, $output) = @_;
    my $rseqid = 0;
    my $fname  = undef;
    my $mtype  = 0;

    $input->readMessageBegin(\$fname, \$mtype, \$rseqid);
    my $methodname = 'process_'.$fname;
    if (!$self->can($methodname)) {
      $input->skip(ElasticSearch::Transport::ThriftBackend::TType::STRUCT);
      $input->readMessageEnd();
      my $x = new ElasticSearch::Transport::ThriftBackend::TApplicationException('Function '.$fname.' not implemented.', ElasticSearch::Transport::ThriftBackend::TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, ElasticSearch::Transport::ThriftBackend::TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $self->$methodname($rseqid, $input, $output);
    return 1;
}

sub process_execute {
    my ($self, $seqid, $input, $output) = @_;
    my $args = new ElasticSearch::Transport::ThriftBackend::Rest_execute_args();
    $args->read($input);
    $input->readMessageEnd();
    my $result = new ElasticSearch::Transport::ThriftBackend::Rest_execute_result();
    $result->{success} = $self->{handler}->execute($args->request);
    $output->writeMessageBegin('execute', ElasticSearch::Transport::ThriftBackend::TMessageType::REPLY, $seqid);
    $result->write($output);
    $output->writeMessageEnd();
    $output->getTransport()->flush();
}

1;
